// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// format_double_cpp
CharacterVector format_double_cpp(NumericVector x, int precision);
RcppExport SEXP _stablehlo_format_double_cpp(SEXP xSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(format_double_cpp(x, precision));
    return rcpp_result_gen;
END_RCPP
}
// format_raw_buffer_cpp
String format_raw_buffer_cpp(RawVector data, std::string dtype, IntegerVector shape);
RcppExport SEXP _stablehlo_format_raw_buffer_cpp(SEXP dataSEXP, SEXP dtypeSEXP, SEXP shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type shape(shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(format_raw_buffer_cpp(data, dtype, shape));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stablehlo_format_double_cpp", (DL_FUNC) &_stablehlo_format_double_cpp, 2},
    {"_stablehlo_format_raw_buffer_cpp", (DL_FUNC) &_stablehlo_format_raw_buffer_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_stablehlo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
