# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

format_c_cpp <- function(x, precision) {
    .Call(`_stablehlo_format_c_cpp`, x, precision)
}

