# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

format_double_cpp <- function(x, precision) {
    .Call(`_stablehlo_format_double_cpp`, x, precision)
}

format_raw_buffer_cpp <- function(data, dtype, shape) {
    .Call(`_stablehlo_format_raw_buffer_cpp`, data, dtype, shape)
}

