on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    permissions:
      contents: write
    uses: r-xla/actions/.github/workflows/pkgdown.yaml@main
    with:
      setup-pjrt: true
