on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage.yaml

permissions:
  id-token: write

jobs:
  test-coverage:
    uses: r-xla/actions/.github/workflows/test-coverage.yaml@main
